apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vcy7
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vcy7
    app.kubernetes.io/part-of: my-node-app
  name: devfile-sample-vcy7
  namespace: sbaird-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vcy7
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vcy7
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:758b4e9d5d6453d1ec9af58aee6a8eba0cfb2aa0fe8fef0be8b55b641b105ace
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
